# Generated by Django 2.2 on 2019-04-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.TextField(max_length=50)),
                ('descr', models.TextField(max_length=500, null=True)),
                ('prio', models.IntegerField(verbose_name='Приоритет поиска')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Типы поиска',
                'verbose_name_plural': 'Типы поиска',
            },
        ),
    ]
