# Generated by Django 2.2 on 2019-04-10 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skip_tools', '0002_auto_20190410_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pull',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.TextField(max_length=50)),
                ('skip_date', models.DateTimeField(null=True)),
                ('prio', models.IntegerField(verbose_name='Приоритет поиска')),
                ('descr', models.TextField(max_length=500, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('source_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='skip_tools.RefSource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Пачки, отправляемые на скип',
                'verbose_name_plural': 'Пачки, отправляемые на скип',
            },
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.TextField(max_length=50)),
                ('search_str', models.TextField(max_length=50)),
                ('search_date', models.DateTimeField()),
                ('batch_id', models.IntegerField(verbose_name='Индентификатор пачки для многопоточности')),
                ('natural_person_id', models.IntegerField()),
                ('date_search', models.DateTimeField(null=True, verbose_name='Дата поиска')),
                ('date_parsed', models.DateTimeField(null=True, verbose_name='Дата парсинга')),
                ('pull_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pull', to='skip_tools.Pull', verbose_name='Блок поиска')),
            ],
            options={
                'verbose_name': 'Основная таблица для логирования поиска',
                'verbose_name_plural': 'Основная таблица для логирования поиска',
            },
        ),
        migrations.DeleteModel(
            name='IvSkip',
        ),
    ]
