# Generated by Django 2.2 on 2019-04-10 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip_tools', '0003_auto_20190410_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pull',
            name='descr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='pull',
            name='search_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='search',
            name='fio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='search',
            name='search_str',
            field=models.CharField(max_length=50),
        ),
    ]
