# Generated by Django 2.2 on 2019-04-11 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skip_tools', '0004_auto_20190410_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_type', models.CharField(max_length=50)),
                ('is_ok', models.CharField(default='N', max_length=1)),
                ('prio', models.IntegerField(verbose_name='Приоритет поиска')),
                ('descr', models.CharField(max_length=500, null=True)),
                ('percent_complete', models.IntegerField(default=0)),
                ('start_dt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('end_dt', models.DateTimeField(null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Задачи на поиск',
                'verbose_name_plural': 'Задачи на поиск',
            },
        ),
        migrations.CreateModel(
            name='TaskFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('file_type', models.CharField(max_length=255, null=True, verbose_name='Тип файла')),
                ('source_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_task_files_source', to='skip_tools.RefSource', verbose_name='Источник')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_task_files_task', to='skip_tools.Task', verbose_name='Блок поиска')),
            ],
            options={
                'verbose_name': 'Файлы, которые прикрепляются к таскам',
                'verbose_name_plural': 'Файлы, которые прикрепляются к таскам',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('template', models.TextField()),
                ('creator', models.CharField(max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Таблица с шаблонами параметров для поиска',
                'verbose_name_plural': 'Таблица с шаблонами параметров для поиска',
            },
        ),
        migrations.RemoveField(
            model_name='search',
            name='pull_id',
        ),
        migrations.AddField(
            model_name='search',
            name='source_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_search_source', to='skip_tools.RefSource', verbose_name='Источник'),
        ),
        migrations.DeleteModel(
            name='Pull',
        ),
        migrations.AddField(
            model_name='task',
            name='template_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_template_task', to='skip_tools.Template', verbose_name='Ссылка на шаблон'),
        ),
        migrations.AddField(
            model_name='search',
            name='task_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_search_task', to='skip_tools.Task', verbose_name='Блок поиска'),
        ),
    ]
