# Generated by Django 2.2 on 2019-04-11 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skip_tools', '0005_auto_20190411_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='source_id',
            new_name='source_link',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='task_id',
            new_name='task_link',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='template_id',
            new_name='template_link',
        ),
        migrations.RenameField(
            model_name='taskfiles',
            old_name='source_id',
            new_name='source_link',
        ),
    ]
