# Generated by Django 2.2 on 2019-04-11 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skip_tools', '0006_auto_20190411_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='source_link',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='search',
            old_name='task_link',
            new_name='task',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='template_link',
            new_name='template',
        ),
        migrations.RenameField(
            model_name='taskfiles',
            old_name='source_link',
            new_name='source',
        ),
        migrations.RenameField(
            model_name='taskfiles',
            old_name='task_id',
            new_name='task',
        ),
    ]
