# Generated by Django 2.2 on 2019-04-12 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skip_tools', '0008_foundmap_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.IntegerField(verbose_name='Индентификатор объекта')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_template_filepackage', to='skip_tools.Template', verbose_name='Ссылка на шаблон')),
            ],
            options={
                'verbose_name': 'Таблица с id, залитыми из файла',
            },
        ),
    ]
