# Generated by Django 2.2 on 2019-04-13 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skip_tools', '0009_filepackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='batch_id',
            field=models.IntegerField(null=True, verbose_name='Индентификатор пачки для многопоточности'),
        ),
        migrations.AlterField(
            model_name='task',
            name='end_dt',
            field=models.DateTimeField(null=True, verbose_name='Дата Завершения'),
        ),
        migrations.AlterField(
            model_name='task',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_template_task', to='skip_tools.Template', verbose_name='template_link'),
        ),
    ]
