# Generated by Django 2.2 on 2019-04-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip_tools', '0010_auto_20190413_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='natural_person_id',
            field=models.IntegerField(null=True),
        ),
    ]
