# Generated by Django 2.2 on 2019-04-13 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skip_tools', '0011_auto_20190413_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='source',
        ),
        migrations.CreateModel(
            name='TemplateSourceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_tempalte_sourcelist_source', to='skip_tools.RefSource', verbose_name='Источник')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_tempalte_sourcelist_template', to='skip_tools.Template', verbose_name='Ссылка на шаблон')),
            ],
        ),
    ]
