# Generated by Django 2.2 on 2019-04-13 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip_tools', '0012_auto_20190413_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='natural_person_id',
        ),
        migrations.AddField(
            model_name='search',
            name='person_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
