# Generated by Django 2.2 on 2019-04-14 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skip_tools', '0013_auto_20190413_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='web_keys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255, null=True)),
                ('provider', models.CharField(max_length=255, null=True, verbose_name='Название провайдера, предоставившего ключ')),
                ('status', models.IntegerField(default=1, verbose_name='1 - активен, 0 - неактивен')),
                ('last_used', models.DateTimeField(null=True, verbose_name='Дата последнего использования')),
                ('n_requests', models.IntegerField(null=True, verbose_name='Счётчик запросов')),
                ('proxy_addr', models.CharField(max_length=255, null=True)),
                ('proxy_user', models.CharField(max_length=255, null=True)),
                ('proxy_pass', models.CharField(max_length=255, null=True)),
                ('date_del', models.DateTimeField(null=True, verbose_name='Дата удаления')),
                ('batch_id', models.IntegerField(null=True, verbose_name='Индентификатор пачки для многопоточности')),
            ],
            options={
                'verbose_name': 'Логины пользователей, прокси адреса',
            },
        ),
        migrations.AddField(
            model_name='template',
            name='source',
            field=models.ManyToManyField(to='skip_tools.RefSource'),
        ),
        migrations.DeleteModel(
            name='TemplateSourceList',
        ),
    ]
